name= "pastebin-worker"
compatibility_date = "2023-12-21"
account_id= "45148885bc21362086394801ab3f2a45"
main = "src/index.ts"
workers_dev = false

vars = { ENVIRONMENT = "production" }
route = { pattern = "paste.2fw.top", custom_domain = true }

kv_namespaces = [
  { binding = "PB", id = "f350a15f1b0043ac9797e7eeefa2cc84" },
  { binding = "PBIMGS", id ="2fc8de5cb16449c3a328e72283536900" }
]

[site]
bucket = "./static/dist"
