name= "pastebin-worker"
compatibility_date = "2023-12-21"
account_id= "45148885bc21362086394801ab3f2a45"
main = "src/index.ts"
workers_dev = false

vars = { ENVIRONMENT = "production" }
route = { pattern = "paste.2fw.top", custom_domain = true }

kv_namespaces = [
  { binding = "pastebin", id = "a8adff9f522b43bd980658054769a1b7" },
  { binding = "pastebin-img", id ="602ccc639a6b40c7a0719dec6a59a260" }
]

[site]
bucket = "./static/dist"
